version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - platform: x86
      nodejs_version: '6'
    - platform: x64
      nodejs_version: '6'
    - platform: x86
      nodejs_version: '4'
    - platform: x64
      nodejs_version: '4'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g grunt-cli
  - npm install

build: off

before_test:
  - node --version
  - npm --version

test_script:
  - ps: grunt test --no-color
  - cmd: grunt test --no-color
